/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Asset
         * @description 纳入并哈希一个模板资产（§11）：复制 → 校验 → 内容寻址落盘 → 入库。
         */
        post: operations["create_asset_api_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect Asset
         * @description 用匹配版本 CAD 读取可用布局（§11）；端口未接线时返回 501。
         *
         *     PLAN-DB-001 Task 4 裁决：本任务只定义 LayoutInspection 端口，
         *     端口未接线固定 501 + CAD_VERSION_UNAVAILABLE；真实 CAD 布局读取
         *     由 Task 7 接线，本端点绝不伪造布局列表。
         */
        post: operations["inspect_asset_api_assets__asset_id__inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cadabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cadabilities
         * @description 只读 capability 响应：两个受支持版本的探测结果（不启动进程）。
         */
        get: operations["get_cadabilities_api_cadabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Project
         * @description 创建项目库（project.dstb）、初始草稿与 assets/、builds/ 目录。
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Project
         * @description 读取项目、当前草稿、引导步骤、聚焦字段与诊断（只读，无副作用）。
         */
        get: operations["get_current_project_api_projects_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/current/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Current Draft
         * @description 带 base_updated_at 乐观并发保存草稿；返回字段级诊断。
         */
        patch: operations["patch_current_draft_api_projects_current_draft_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetInspectionResponse
         * @description 布局 inspection 结果；端口未接线时端点返回 501 错误负载。
         */
        AssetInspectionResponse: {
            /** Asset Id */
            asset_id: string;
            /** Cad Version */
            cad_version: string;
            /** Layouts */
            layouts: string[];
        };
        /**
         * AssetInspectRequest
         * @description POST /api/assets/{id}/inspect 请求：指定匹配版本的 CAD。
         */
        AssetInspectRequest: {
            /**
             * Cad Version
             * @enum {string}
             */
            cad_version: "2016" | "2020";
        };
        /**
         * AssetIntakeRequest
         * @description POST /api/assets 请求：纳入一个本机源文件（ Builder 为本地应用，
         *     源文件经路径引用而非 HTTP 上传，避免 2 GiB 文件流经接口层）。
         */
        AssetIntakeRequest: {
            /**
             * Role
             * @enum {string}
             */
            role: "base" | "layout";
            /** Source Path */
            source_path: string;
        };
        /**
         * AssetModel
         * @description 纳入结果：内容寻址相对路径与固定哈希（§3 assets 表投影）。
         */
        AssetModel: {
            /** Id */
            id: string;
            /** Relative Path */
            relative_path: string;
            /** Role */
            role: string;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
            /** Source Name */
            source_name: string;
        };
        /**
         * CadCapabilitiesResponse
         * @description GET /api/cadabilities 响应：两个受支持版本的探测结果。
         */
        CadCapabilitiesResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["CadCapabilityModel"][];
        };
        /**
         * CadCapabilityModel
         * @description 单个 CAD 版本的只读能力探测结果。
         */
        CadCapabilityModel: {
            /** Available */
            available: boolean;
            /** Cad Version */
            cad_version: string;
            /** Console Path */
            console_path?: string | null;
            /** Plugin Path */
            plugin_path?: string | null;
            /** Unavailable Reason */
            unavailable_reason?: string | null;
        };
        /** DiagnosticModel */
        DiagnosticModel: {
            /** Code */
            code: string;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
        };
        /**
         * DraftFieldsModel
         * @description §4 DraftProjectV1 JSON 形态（PATCH 载荷的解析与校验目标）。
         */
        DraftFieldsModel: {
            /** Cad Version */
            cad_version: string;
            numbering: components["schemas"]["NumberingFieldsModel"];
            project: components["schemas"]["ProjectFieldsModel"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Sheets */
            sheets: components["schemas"]["SheetFieldsModel"][];
            template: components["schemas"]["TemplateFieldsModel"];
        };
        /**
         * DraftPatchRequest
         * @description PATCH /api/projects/current/draft 请求：base_updated_at 乐观并发。
         */
        DraftPatchRequest: {
            /** Base Updated At */
            base_updated_at: string;
            draft: components["schemas"]["DraftFieldsModel"];
            /** Focused Field */
            focused_field?: string | null;
            /** Wizard Step */
            wizard_step: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NumberingFieldsModel */
        NumberingFieldsModel: {
            /** Prefix */
            prefix: string;
            /** Start */
            start: number;
            /** Width */
            width: number;
        };
        /**
         * ProjectCreateRequest
         * @description POST /api/projects 请求。``project_root`` 仅在应用工厂未绑定根目录时必填。
         */
        ProjectCreateRequest: {
            /** Discipline */
            discipline: string;
            /** Name */
            name: string;
            /** Output Path */
            output_path: string;
            /** Project Root */
            project_root?: string | null;
            /** Stage */
            stage: string;
        };
        /** ProjectFieldsModel */
        ProjectFieldsModel: {
            /** Discipline */
            discipline: string;
            /** Name */
            name: string;
            /** Output Path */
            output_path: string;
            /** Stage */
            stage: string;
        };
        /** ProjectModel */
        ProjectModel: {
            /** Created At */
            created_at: string;
            /** Discipline */
            discipline: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Output Path */
            output_path: string;
            /** Stage */
            stage: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * ProjectStateResponse
         * @description GET /api/projects/current 与 PATCH /api/projects/current/draft 响应。
         */
        ProjectStateResponse: {
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticModel"][];
            draft: components["schemas"]["DraftFieldsModel"];
            /** Focused Field */
            focused_field: string | null;
            project: components["schemas"]["ProjectModel"];
            /** Updated At */
            updated_at: string;
            /** Wizard Step */
            wizard_step: number;
        };
        /** SheetFieldsModel */
        SheetFieldsModel: {
            /** Title */
            title: string;
        };
        /** TemplateFieldsModel */
        TemplateFieldsModel: {
            /** Base Asset Id */
            base_asset_id: string;
            /** Layout Asset Id */
            layout_asset_id: string;
            /** Source Layout */
            source_layout: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_asset_api_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetIntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_asset_api_assets__asset_id__inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetInspectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetInspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cadabilities_api_cadabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CadCapabilitiesResponse"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_project_api_projects_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateResponse"];
                };
            };
        };
    };
    patch_current_draft_api_projects_current_draft_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
