/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Asset
         * @description 纳入并哈希一个模板资产（§11）：复制 → 校验 → 内容寻址落盘 → 入库。
         */
        post: operations["create_asset_api_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect Asset
         * @description 用匹配版本 CAD 读取可用布局（§11）。
         *
         *     生产默认惰性装配 CoreConsoleDrawingBuilder（Task 4"端口未接线固定
         *     501"已由真实执行器接线取代）；CAD 版本未配置或不可用时仍以
         *     CAD_VERSION_UNAVAILABLE（501）呈现，绝不伪造布局列表。
         */
        post: operations["inspect_asset_api_assets__asset_id__inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Build
         * @description 基于已确认计划创建 build/attempt 并在线程执行器中启动构建。
         */
        post: operations["start_build_api_builds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{build_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Build
         * @description 读取状态、诊断和成果（§11）。
         */
        get: operations["get_build_api_builds__build_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{build_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Build
         * @description 请求安全取消（§6）：检查点处迁移 CANCELLED；PUBLISHING 拒绝。
         */
        post: operations["cancel_build_api_builds__build_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{build_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Build Events
         * @description SSE 事件流与重放（§6）：Last-Event-ID 之后的事件按序重放。
         */
        get: operations["stream_build_events_api_builds__build_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cadabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cadabilities
         * @description 只读 capability 响应：两个受支持版本的探测结果（不启动进程）。
         */
        get: operations["get_cadabilities_api_cadabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Plan
         * @description 提交修订并产生预览计划（§5）：确定性 ID，不自动确认。
         */
        post: operations["submit_plan_api_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Plan
         * @description 用户显式确认计划（绝不自动确认）；确认后构建输入冻结。
         */
        post: operations["confirm_plan_api_plans__plan_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Project
         * @description 创建项目库；目录已是 Builder 项目时幂等打开（opened_existing=True，200）。
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Project
         * @description 读取项目、当前草稿、引导步骤、聚焦字段与诊断（只读，无副作用）。
         */
        get: operations["get_current_project_api_projects_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/current/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Current Draft
         * @description 带 base_updated_at 乐观并发保存草稿；返回字段级诊断。
         */
        patch: operations["patch_current_draft_api_projects_current_draft_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetInspectionResponse
         * @description 布局 inspection 结果；端口未接线时端点返回 501 错误负载。
         */
        AssetInspectionResponse: {
            /** Asset Id */
            asset_id: string;
            /** Cad Version */
            cad_version: string;
            /** Layouts */
            layouts: string[];
        };
        /**
         * AssetInspectRequest
         * @description POST /api/assets/{id}/inspect 请求：指定匹配版本的 CAD。
         */
        AssetInspectRequest: {
            /**
             * Cad Version
             * @enum {string}
             */
            cad_version: "2016" | "2020";
        };
        /**
         * AssetIntakeRequest
         * @description POST /api/assets 请求：纳入一个本机源文件（ Builder 为本地应用，
         *     源文件经路径引用而非 HTTP 上传，避免 2 GiB 文件流经接口层）。
         */
        AssetIntakeRequest: {
            /**
             * Role
             * @enum {string}
             */
            role: "base" | "layout";
            /** Source Path */
            source_path: string;
        };
        /**
         * AssetModel
         * @description 纳入结果：内容寻址相对路径与固定哈希（§3 assets 表投影）。
         */
        AssetModel: {
            /** Id */
            id: string;
            /** Relative Path */
            relative_path: string;
            /** Role */
            role: string;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
            /** Source Name */
            source_name: string;
        };
        /**
         * BuildAttemptModel
         * @description 单个 attempt 的状态投影（历史不覆盖）。
         */
        BuildAttemptModel: {
            /** Attempt */
            attempt: number;
            /** Error Code */
            error_code?: string | null;
            /** Progress */
            progress: number;
            /** Status */
            status: string;
        };
        /**
         * BuildStartRequest
         * @description POST /api/builds 请求：基于已确认计划创建 build/attempt。
         */
        BuildStartRequest: {
            /** Plan Id */
            plan_id: string;
        };
        /**
         * BuildStatusResponse
         * @description GET /api/builds/{id}、POST /api/builds、POST .../cancel 响应。
         */
        BuildStatusResponse: {
            /** Attempt */
            attempt: number;
            /** Attempts */
            attempts: components["schemas"]["BuildAttemptModel"][];
            /** Build Id */
            build_id: string;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Error Detail */
            error_detail?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Plan Id */
            plan_id: string;
            /** Progress */
            progress: number;
            /** Published Path */
            published_path?: string | null;
            /** Status */
            status: string;
        };
        /**
         * CadCapabilitiesResponse
         * @description GET /api/cadabilities 响应：两个受支持版本的探测结果。
         */
        CadCapabilitiesResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["CadCapabilityModel"][];
        };
        /**
         * CadCapabilityModel
         * @description 单个 CAD 版本的只读能力探测结果。
         */
        CadCapabilityModel: {
            /** Available */
            available: boolean;
            /** Cad Version */
            cad_version: string;
            /** Console Path */
            console_path?: string | null;
            /** Plugin Path */
            plugin_path?: string | null;
            /** Unavailable Reason */
            unavailable_reason?: string | null;
        };
        /** DiagnosticModel */
        DiagnosticModel: {
            /** Code */
            code: string;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
        };
        /**
         * DraftFieldsModel
         * @description §4 DraftProjectV1 JSON 形态（PATCH 载荷的解析与校验目标）。
         */
        DraftFieldsModel: {
            /** Cad Version */
            cad_version: string;
            numbering: components["schemas"]["NumberingFieldsModel"];
            project: components["schemas"]["ProjectFieldsModel"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Sheets */
            sheets: components["schemas"]["SheetFieldsModel"][];
            template: components["schemas"]["TemplateFieldsModel"];
        };
        /**
         * DraftPatchRequest
         * @description PATCH /api/projects/current/draft 请求：base_updated_at 乐观并发。
         */
        DraftPatchRequest: {
            /** Base Updated At */
            base_updated_at: string;
            draft: components["schemas"]["DraftFieldsModel"];
            /** Focused Field */
            focused_field?: string | null;
            /** Wizard Step */
            wizard_step: number;
        };
        /**
         * ErrorPayloadModel
         * @description 所有非 2xx 响应的统一负载；``code`` 只使用 §11 固定错误码。
         */
        ErrorPayloadModel: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
            /** Recovery Action */
            recovery_action: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NumberingFieldsModel */
        NumberingFieldsModel: {
            /** Prefix */
            prefix: string;
            /** Start */
            start: number;
            /** Width */
            width: number;
        };
        /**
         * PlanConfirmationResponse
         * @description POST /api/plans/{id}/confirm 响应。
         */
        PlanConfirmationResponse: {
            /** Confirmed At */
            confirmed_at: string;
            /** Plan Id */
            plan_id: string;
            /** Revision Id */
            revision_id: string;
        };
        /**
         * PlanPreviewModel
         * @description 计划预览派生值（§4/§5）。
         */
        PlanPreviewModel: {
            /** Artifact Path */
            artifact_path: string;
            /** Cad Version */
            cad_version: string;
            /** Dst Path */
            dst_path: string;
            /** Dwg Name */
            dwg_name: string;
            /** Layout Name */
            layout_name: string;
            /** Sheet Number */
            sheet_number: string;
            /** Sheetset Name */
            sheetset_name: string;
            /** Subset Name */
            subset_name: string;
        };
        /**
         * PlanSubmitResponse
         * @description POST /api/plans 响应：确定性计划 ID 与构建前诊断。
         */
        PlanSubmitResponse: {
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticModel"][];
            /** Plan Id */
            plan_id: string;
            /** Plan Sha256 */
            plan_sha256: string;
            preview: components["schemas"]["PlanPreviewModel"];
            /** Revision Id */
            revision_id: string;
            /** Revision Sha256 */
            revision_sha256: string;
        };
        /**
         * ProjectCreateRequest
         * @description POST /api/projects 请求。``project_root`` 仅在应用工厂未绑定根目录时必填。
         */
        ProjectCreateRequest: {
            /** Discipline */
            discipline: string;
            /** Name */
            name: string;
            /** Output Path */
            output_path: string;
            /** Project Root */
            project_root?: string | null;
            /** Stage */
            stage: string;
        };
        /** ProjectFieldsModel */
        ProjectFieldsModel: {
            /** Discipline */
            discipline: string;
            /** Name */
            name: string;
            /** Output Path */
            output_path: string;
            /** Stage */
            stage: string;
        };
        /** ProjectModel */
        ProjectModel: {
            /** Created At */
            created_at: string;
            /** Discipline */
            discipline: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Output Path */
            output_path: string;
            /** Stage */
            stage: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * ProjectStateResponse
         * @description GET /api/projects/current 与 PATCH /api/projects/current/draft 响应。
         */
        ProjectStateResponse: {
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticModel"][];
            draft: components["schemas"]["DraftFieldsModel"];
            /** Focused Field */
            focused_field: string | null;
            /**
             * Opened Existing
             * @default false
             */
            opened_existing: boolean;
            project: components["schemas"]["ProjectModel"];
            /** Updated At */
            updated_at: string;
            /** Wizard Step */
            wizard_step: number;
        };
        /** SheetFieldsModel */
        SheetFieldsModel: {
            /** Title */
            title: string;
        };
        /** TemplateFieldsModel */
        TemplateFieldsModel: {
            /** Base Asset Id */
            base_asset_id: string;
            /** Layout Asset Id */
            layout_asset_id: string;
            /** Source Layout */
            source_layout: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_asset_api_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetIntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_asset_api_assets__asset_id__inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetInspectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetInspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 布局 inspection 端口未接线或匹配版本 CAD 不可用（CAD_VERSION_UNAVAILABLE） */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
        };
    };
    start_build_api_builds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildStatusResponse"];
                };
            };
            /** @description 计划不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
            /** @description PLAN_STALE / PACKAGE_TARGET_EXISTS / BUILD_ALREADY_RUNNING */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
            /** @description PLAN_NOT_CONFIRMED */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
        };
    };
    get_build_api_builds__build_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildStatusResponse"];
                };
            };
            /** @description 构建不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_build_api_builds__build_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildStatusResponse"];
                };
            };
            /** @description 构建不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
            /** @description PUBLISHING 或终止状态不响应取消（CANCEL_NOT_ACCEPTED） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_build_events_api_builds__build_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 事件流（id: attempt:sequence） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 构建不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cadabilities_api_cadabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CadCapabilitiesResponse"];
                };
            };
        };
    };
    submit_plan_api_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSubmitResponse"];
                };
            };
        };
    };
    confirm_plan_api_plans__plan_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanConfirmationResponse"];
                };
            };
            /** @description 计划不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
            /** @description PLAN_STALE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
            /** @description 存在阻断诊断 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPayloadModel"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_project_api_projects_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateResponse"];
                };
            };
        };
    };
    patch_current_draft_api_projects_current_draft_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
