/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/custom-properties/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Custom Property Template */
        get: operations["custom_property_template_api_custom_properties_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layout-names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read Layout Names */
        post: operations["read_layout_names_api_layout_names_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revisions */
        get: operations["revisions_api_revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/cad-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_system_cad_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/changes/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_api_workspaces__workspace_id__changes_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/changes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_workspaces__workspace_id__changes_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/custom-properties/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Custom Properties */
        get: operations["export_custom_properties_api_workspaces__workspace_id__custom_properties_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/custom-properties/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Custom Properties */
        post: operations["import_custom_properties_api_workspaces__workspace_id__custom_properties_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/custom-properties/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Custom Property Import */
        post: operations["preview_custom_property_import_api_workspaces__workspace_id__custom_properties_import_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_workspaces__workspace_id__draft_get"];
        /** Put Draft */
        put: operations["put_draft_api_workspaces__workspace_id__draft_put"];
        post?: never;
        /** Delete Draft */
        delete: operations["delete_draft_api_workspaces__workspace_id__draft_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/repairs/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repair Execute */
        post: operations["repair_execute_api_workspaces__workspace_id__repairs_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/repairs/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repair Preview */
        post: operations["repair_preview_api_workspaces__workspace_id__repairs_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/revisions/{revision_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Revision */
        post: operations["restore_revision_api_workspaces__workspace_id__revisions__revision_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/revisions/{revision_id}/restore-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Restore Preview */
        get: operations["restore_preview_api_workspaces__workspace_id__revisions__revision_id__restore_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/xml/export-dst": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Dst */
        post: operations["export_dst_api_workspaces__workspace_id__xml_export_dst_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/xml/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Xml */
        post: operations["preview_xml_api_workspaces__workspace_id__xml_import_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Workspace */
        post: operations["open_workspace_api_workspaces_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCustomPropertyCommand */
        AddCustomPropertyCommand: {
            /**
             * Default Value
             * @default
             */
            default_value: string;
            /** Name */
            name: string;
            /**
             * Property Type
             * @enum {string}
             */
            property_type: "sheetset" | "sheet";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "add_custom_property";
        };
        /** CadCapabilitiesResponse */
        CadCapabilitiesResponse: {
            [key: string]: components["schemas"]["CadCapabilityResponse"];
        };
        /** CadCapabilityResponse */
        CadCapabilityResponse: {
            /** Available */
            available: boolean;
            /** Console */
            console?: string | null;
            /** Plugin */
            plugin?: string | null;
            /** Version */
            version: string;
        };
        /** CadGroupResponse */
        CadGroupResponse: {
            /**
             * Cad Operation
             * @enum {string}
             */
            cad_operation: "rename_only" | "rebuild";
            /** Expected Baseline */
            expected_baseline?: null;
            /** Layouts */
            layouts: components["schemas"]["PlannedLayoutResponse"][];
            /**
             * Operation
             * @enum {string}
             */
            operation: "create" | "rebuild";
            /** Source Snapshot */
            source_snapshot: string;
            /** Source Target File */
            source_target_file: string | null;
            /** Subset Id */
            subset_id: string;
            /** Subset Name */
            subset_name: string;
            /** Target File */
            target_file: string;
            /** Target Reuses Source */
            target_reuses_source: boolean;
        };
        /** CardinalityFrontierResponse */
        CardinalityFrontierResponse: {
            /** Index */
            index: number;
            /** Subset Id */
            subset_id: string | null;
        };
        /** ChangeExecuteRequest */
        ChangeExecuteRequest: {
            /** Base Revision Id */
            base_revision_id: string;
            /**
             * Cad Version
             * @default 2020
             * @enum {string}
             */
            cad_version: "2016" | "2020";
            /** Commands */
            commands?: (components["schemas"]["UpdateSheetSetCommand"] | components["schemas"]["UpdateSubsetTitleCommand"] | components["schemas"]["UpdateSheetPropertiesCommand"] | components["schemas"]["DeleteSheetCommand"] | components["schemas"]["InsertSheetCommand"] | components["schemas"]["InsertSubsetCommand"] | components["schemas"]["AddCustomPropertyCommand"] | components["schemas"]["DeleteCustomPropertyCommand"] | components["schemas"]["DeleteSubsetCommand"])[];
            /** Preview Digest */
            preview_digest: string;
        };
        /** ChangePreviewRequest */
        ChangePreviewRequest: {
            /** Base Revision Id */
            base_revision_id: string;
            /**
             * Cad Version
             * @default 2020
             * @enum {string}
             */
            cad_version: "2016" | "2020";
            /** Commands */
            commands?: (components["schemas"]["UpdateSheetSetCommand"] | components["schemas"]["UpdateSubsetTitleCommand"] | components["schemas"]["UpdateSheetPropertiesCommand"] | components["schemas"]["DeleteSheetCommand"] | components["schemas"]["InsertSheetCommand"] | components["schemas"]["InsertSubsetCommand"] | components["schemas"]["AddCustomPropertyCommand"] | components["schemas"]["DeleteCustomPropertyCommand"] | components["schemas"]["DeleteSubsetCommand"])[];
        };
        /** ChangePreviewResponse */
        ChangePreviewResponse: {
            /** Affected Files */
            affected_files: string[];
            /** Base Revision Id */
            base_revision_id: string;
            /**
             * Cad Version
             * @enum {string}
             */
            cad_version: "2016" | "2020";
            /** Changes */
            changes: (components["schemas"]["CommandChangeResponse"] | components["schemas"]["PropertyCsvChangeResponse"])[];
            /** Commands */
            commands?: (components["schemas"]["UpdateSheetSetCommand"] | components["schemas"]["UpdateSubsetTitleCommand"] | components["schemas"]["UpdateSheetPropertiesCommand"] | components["schemas"]["DeleteSheetCommand"] | components["schemas"]["InsertSheetCommand"] | components["schemas"]["InsertSubsetCommand"] | components["schemas"]["AddCustomPropertyCommand"] | components["schemas"]["DeleteCustomPropertyCommand"] | components["schemas"]["DeleteSubsetCommand"])[] | null;
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticResponse"][];
            /** Executable */
            executable: boolean;
            execution_intent?: components["schemas"]["ExecutionIntentResponse"] | null;
            /** Preview Digest */
            preview_digest: string;
            /** Requires Cad */
            requires_cad: boolean;
            semantic_diff: components["schemas"]["SemanticDiffResponse"];
            /** Workspace Id */
            workspace_id: string;
        };
        /** CommandChangeResponse */
        CommandChangeResponse: {
            /** Affected Sheet Count */
            affected_sheet_count?: number | null;
            /** After */
            after: (components["schemas"]["UpdateSheetSetCommand"] | components["schemas"]["UpdateSubsetTitleCommand"] | components["schemas"]["UpdateSheetPropertiesCommand"] | components["schemas"]["DeleteSheetCommand"] | components["schemas"]["InsertSheetCommand"] | components["schemas"]["InsertSubsetCommand"] | components["schemas"]["AddCustomPropertyCommand"] | components["schemas"]["DeleteCustomPropertyCommand"] | components["schemas"]["DeleteSubsetCommand"]) | components["schemas"]["NormalizedUpdateSubsetCommand"] | components["schemas"]["NormalizedUpdateSheetCommand"];
            /** Index */
            index: number;
            /** Object Id */
            object_id?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "update_sheet_set" | "update_subset" | "update_sheet" | "delete_sheet" | "insert_sheet" | "insert_subset" | "add_custom_property" | "delete_custom_property" | "delete_subset";
        };
        /** DeleteCustomPropertyCommand */
        DeleteCustomPropertyCommand: {
            /** Name */
            name: string;
            /**
             * Property Type
             * @enum {string}
             */
            property_type: "sheetset" | "sheet";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delete_custom_property";
        };
        /** DeletedSubsetResponse */
        DeletedSubsetResponse: {
            /** Subset Id */
            subset_id: string;
            /** Target File */
            target_file: string;
        };
        /** DeleteSheetCommand */
        DeleteSheetCommand: {
            /** Sheet Id */
            sheet_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delete_sheet";
        };
        /** DeleteSubsetCommand */
        DeleteSubsetCommand: {
            /**
             * Confirm Delete All Sheets
             * @constant
             */
            confirm_delete_all_sheets: true;
            /**
             * Confirm Delete Main Dwg
             * @constant
             */
            confirm_delete_main_dwg: true;
            /** Subset Id */
            subset_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delete_subset";
        };
        /** DerivedDocumentResponse */
        DerivedDocumentResponse: {
            /** Affected Subset Ids */
            affected_subset_ids: string[];
            /** Layout Sources */
            layout_sources: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            property_diff: components["schemas"]["PropertyDefinitionDiffResponse"];
            /** Subsets */
            subsets: components["schemas"]["DerivedSubsetResponse"][];
        };
        /** DerivedLayoutResponse */
        DerivedLayoutResponse: {
            /** File Name */
            file_name: string;
            /** Handle */
            handle: string;
            /** Layout Name */
            layout_name: string;
            /** Relative File Name */
            relative_file_name: string;
            /** Resolution Source */
            resolution_source?: string | null;
            /** Resolved Path */
            resolved_path?: string | null;
        };
        /** DerivedSheetResponse */
        DerivedSheetResponse: {
            /** Acsm Id */
            acsm_id: string;
            /** Custom Properties */
            custom_properties: {
                [key: string]: string;
            };
            layout: components["schemas"]["DerivedLayoutResponse"];
            /** Number */
            number: string;
            /** Title */
            title: string;
        };
        /** DerivedSubsetResponse */
        DerivedSubsetResponse: {
            /** Acsm Id */
            acsm_id: string;
            /** Display Name */
            display_name: string;
            /** Number Range */
            number_range: string;
            /** Sheets */
            sheets: components["schemas"]["DerivedSheetResponse"][];
            /** Source Target File */
            source_target_file: string;
            /** Target File */
            target_file: string;
            /** Title */
            title: string;
        };
        /** DiagnosticResponse */
        DiagnosticResponse: {
            /** Code */
            code: string;
            /** Index */
            index?: number | null;
            /** Line */
            line?: number | null;
            /** Location */
            location?: string | null;
            /** Message */
            message: string;
            /** Object Id */
            object_id?: string | null;
            /** Property Name */
            property_name?: string | null;
            /** Severity */
            severity: string;
        };
        /** DraftAction */
        DraftAction: {
            /** Commands */
            commands: (components["schemas"]["UpdateSheetSetCommand"] | components["schemas"]["UpdateSubsetTitleCommand"] | components["schemas"]["UpdateSheetPropertiesCommand"] | components["schemas"]["DeleteSheetCommand"] | components["schemas"]["InsertSheetCommand"] | components["schemas"]["InsertSubsetCommand"] | components["schemas"]["AddCustomPropertyCommand"] | components["schemas"]["DeleteCustomPropertyCommand"] | components["schemas"]["DeleteSubsetCommand"])[];
            /** Id */
            id: string;
            /**
             * Kind
             * @constant
             */
            kind: "command_batch";
            /** Label */
            label: string;
        };
        /** DraftActionResponse */
        DraftActionResponse: {
            /** Commands */
            commands: (components["schemas"]["UpdateSheetSetCommand"] | components["schemas"]["UpdateSubsetTitleCommand"] | components["schemas"]["UpdateSheetPropertiesCommand"] | components["schemas"]["DeleteSheetCommand"] | components["schemas"]["InsertSheetCommand"] | components["schemas"]["InsertSubsetCommand"] | components["schemas"]["AddCustomPropertyCommand"] | components["schemas"]["DeleteCustomPropertyCommand"] | components["schemas"]["DeleteSubsetCommand"])[];
            /** Id */
            id: string;
            /**
             * Kind
             * @constant
             */
            kind: "command_batch";
            /** Label */
            label: string;
        };
        /** DraftDeleteRequest */
        DraftDeleteRequest: {
            /** Expected Version */
            expected_version: number;
        };
        /** DraftDeleteResponse */
        DraftDeleteResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /** DraftDocumentResponse */
        DraftDocumentResponse: {
            /** Actions */
            actions: components["schemas"]["DraftActionResponse"][];
            /** Base Revision Id */
            base_revision_id: string;
            /** Cursor */
            cursor: number;
            /**
             * Repair Status
             * @enum {string}
             */
            repair_status: "VALID" | "REPAIRED" | "INVALID_REPAIR_REQUIRED" | "INVALID_UNRECOVERABLE";
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Version */
            version: number;
            /** Workspace Id */
            workspace_id: string;
        };
        /** DraftEnvelopeResponse */
        DraftEnvelopeResponse: {
            /** Corrupted */
            corrupted: boolean;
            draft: components["schemas"]["DraftDocumentResponse"] | null;
            /** Stale */
            stale: boolean;
            /** Stale Reasons */
            stale_reasons: string[];
        };
        /** DraftPutRequest */
        DraftPutRequest: {
            /** Actions */
            actions?: components["schemas"]["DraftAction"][];
            /** Base Revision Id */
            base_revision_id: string;
            /** Cursor */
            cursor: number;
            /** Expected Version */
            expected_version: number;
            /**
             * Repair Status
             * @enum {string}
             */
            repair_status: "VALID" | "REPAIRED" | "INVALID_REPAIR_REQUIRED" | "INVALID_UNRECOVERABLE";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** DstValidationResponse */
        DstValidationResponse: {
            /** Actions */
            actions?: components["schemas"]["RepairActionResponse"][];
            /** Blocking Issues */
            blocking_issues?: components["schemas"]["DiagnosticResponse"][];
            /**
             * Status
             * @enum {string}
             */
            status: "VALID" | "REPAIRED" | "INVALID_REPAIR_REQUIRED" | "INVALID_UNRECOVERABLE";
        };
        /** DwgDiffResponse */
        DwgDiffResponse: {
            /**
             * Action
             * @enum {string}
             */
            action: "create" | "rebuild" | "delete";
            after: components["schemas"]["DwgLayoutSnapshotResponse"] | null;
            before: components["schemas"]["DwgLayoutSnapshotResponse"] | null;
            /** Subset Id */
            subset_id: string;
        };
        /** DwgLayoutSnapshotResponse */
        DwgLayoutSnapshotResponse: {
            /** File */
            file: string;
            /** Layouts */
            layouts: string[];
        };
        /** EstimateDurationResponse */
        EstimateDurationResponse: {
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
        };
        /** EstimateSourceResponse */
        EstimateSourceResponse: {
            /**
             * Cad Operation
             * @enum {string}
             */
            cad_operation: "rename_only" | "rebuild";
            /** Sample Count */
            sample_count: number;
            /**
             * Source
             * @enum {string}
             */
            source: "history" | "fallback-v1";
        };
        /** ExecutionEstimateResponse */
        ExecutionEstimateResponse: {
            /** Concurrency */
            concurrency: number;
            /** Core Console Count */
            core_console_count: number;
            duration_ms: components["schemas"]["EstimateDurationResponse"];
            /**
             * Estimated
             * @constant
             */
            estimated: true;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Sources */
            sources: components["schemas"]["EstimateSourceResponse"][];
        };
        /** ExecutionIntentResponse */
        ExecutionIntentResponse: {
            /** Affected Subset Ids */
            affected_subset_ids: string[];
            /**
             * Cad Validation Deferred
             * @default false
             */
            cad_validation_deferred: boolean;
            cardinality_frontier: components["schemas"]["CardinalityFrontierResponse"] | null;
            /** Deleted Subsets */
            deleted_subsets: components["schemas"]["DeletedSubsetResponse"][];
            derived_document: components["schemas"]["DerivedDocumentResponse"];
            estimate?: components["schemas"]["ExecutionEstimateResponse"] | null;
            /** Expected File Hashes */
            expected_file_hashes?: {
                [key: string]: string | null;
            };
            /** Groups */
            groups: components["schemas"]["CadGroupResponse"][];
            path_graph: components["schemas"]["PathGraphResponse"];
            /** Source Baselines */
            source_baselines?: components["schemas"]["SourceBaselineResponse"][];
            /** Subset Operations */
            subset_operations: components["schemas"]["SubsetOperationResponse"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Run Id */
            run_id?: string | null;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsertSheetCommand */
        InsertSheetCommand: {
            /**
             * Count
             * @default 1
             */
            count: number;
            /** Ordinal */
            ordinal?: number | null;
            /**
             * Placement
             * @default after
             * @enum {string}
             */
            placement: "before" | "after";
            source: components["schemas"]["LayoutSource"];
            /** Target Subset Id */
            target_subset_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "insert_sheet";
        };
        /** InsertSubsetCommand */
        InsertSubsetCommand: {
            /** Base Template File */
            base_template_file: string;
            /**
             * Initial Sheet Count
             * @default 1
             */
            initial_sheet_count: number;
            /** Ordinal */
            ordinal?: number | null;
            /**
             * Placement
             * @default after
             * @enum {string}
             */
            placement: "before" | "after";
            source: components["schemas"]["LayoutSource"];
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "insert_subset";
        };
        /** JobFileResponse */
        JobFileResponse: {
            /** Before Hash */
            before_hash?: string | null;
            /** Cad Operation */
            cad_operation?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Detail */
            error_detail?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Log Path */
            log_path?: string | null;
            /** Log Summary */
            log_summary?: string | null;
            /** Peak Memory Bytes */
            peak_memory_bytes?: number | null;
            /** Progress */
            progress: number;
            /** Result Hash */
            result_hash?: string | null;
            /** Role */
            role?: string | null;
            /** Source Path */
            source_path?: string | null;
            /** Staging Bytes */
            staging_bytes?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Target Path */
            target_path: string;
        };
        /** JobResponse */
        JobResponse: {
            /** Attempt */
            attempt?: number | null;
            /** Cad Version */
            cad_version?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Detail */
            error_detail?: string | null;
            /** Files */
            files?: components["schemas"]["JobFileResponse"][];
            /** Finished At */
            finished_at?: string | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /** Id */
            id: string | null;
            /** No Op */
            no_op?: boolean | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Progress */
            progress?: number | null;
            /** Revision Id */
            revision_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Suggestion */
            suggestion?: string | null;
            summary?: components["schemas"]["JobSummaryResponse"] | null;
            /** Timeline */
            timeline?: {
                [key: string]: unknown;
            }[];
            /** Type */
            type?: string | null;
            /** Worker Id */
            worker_id?: string | null;
            /** Workspace Id */
            workspace_id: string;
        };
        /** JobSummaryResponse */
        JobSummaryResponse: {
            /** Duration Ms */
            duration_ms: number;
            /** Failed */
            failed: number;
            /** Succeeded */
            succeeded: number;
            /** Total */
            total: number;
        };
        /** LayoutNamesRequest */
        LayoutNamesRequest: {
            /**
             * Cad Version
             * @default 2020
             * @enum {string}
             */
            cad_version: "2016" | "2020";
            /**
             * File Path
             * Format: path
             */
            file_path: string;
        };
        /** LayoutNamesResponse */
        LayoutNamesResponse: {
            /** Cached */
            cached: boolean;
            /** File Hash */
            file_hash: string;
            /** Layouts */
            layouts: string[];
        };
        /** LayoutResponse */
        LayoutResponse: {
            /** File Name */
            file_name: string;
            /** Handle */
            handle: string;
            /** Layout Name */
            layout_name: string;
            /** Relative File Name */
            relative_file_name: string;
            /** Resolution Source */
            resolution_source?: string | null;
            /** Resolved Path */
            resolved_path?: string | null;
        };
        /** LayoutSource */
        LayoutSource: {
            /**
             * File
             * @default
             */
            file: string;
            /**
             * Layout
             * @default
             */
            layout: string;
            /**
             * Type
             * @enum {string}
             */
            type: "existing_snapshot" | "template_layout";
        };
        /** NormalizedUpdateSheetCommand */
        NormalizedUpdateSheetCommand: {
            /** Custom Properties */
            custom_properties: {
                [key: string]: string;
            };
            /** Sheet Id */
            sheet_id: string;
            /**
             * Type
             * @constant
             */
            type: "update_sheet";
        };
        /** NormalizedUpdateSubsetCommand */
        NormalizedUpdateSubsetCommand: {
            /** Subset Id */
            subset_id: string;
            /** Title */
            title: string;
            /**
             * Type
             * @constant
             */
            type: "update_subset";
        };
        /** OpenRequest */
        OpenRequest: {
            /**
             * Dst Path
             * Format: path
             */
            dst_path: string;
            /** Root Override */
            root_override?: string | null;
        };
        /** PathGraphResponse */
        PathGraphResponse: {
            /** Delete Targets */
            delete_targets: string[];
            /** Final Targets */
            final_targets: string[];
            /** Old Sources */
            old_sources: string[];
            /** Reused Targets */
            reused_targets: string[];
            /** Transitions */
            transitions: components["schemas"]["PathTransitionResponse"][];
        };
        /** PathTransitionResponse */
        PathTransitionResponse: {
            /**
             * Operation
             * @enum {string}
             */
            operation: "create" | "rebuild";
            /** Source */
            source: string | null;
            /** Subset Id */
            subset_id: string;
            /** Target */
            target: string;
        };
        /** PlannedLayoutResponse */
        PlannedLayoutResponse: {
            /** Custom Properties */
            custom_properties: {
                [key: string]: string;
            };
            /** Number */
            number: string;
            /** Original Layout */
            original_layout?: string | null;
            /** Sheet Id */
            sheet_id: string;
            /** Source File */
            source_file: string;
            /** Source Layout */
            source_layout: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "existing_snapshot" | "template_layout";
            /** Target Layout */
            target_layout: string;
            /** Title */
            title: string;
        };
        /** PropertyCsvChangeResponse */
        PropertyCsvChangeResponse: {
            /**
             * Action
             * @enum {string}
             */
            action: "add" | "skip" | "conflict";
            /** Affected Sheet Count */
            affected_sheet_count: number;
            /** Default Value */
            default_value: string;
            /** Line */
            line: number;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "sheetset" | "sheet";
        };
        /** PropertyCsvExecuteRequest */
        PropertyCsvExecuteRequest: {
            /** Base Revision Id */
            base_revision_id: string;
            /** Csv */
            csv: string;
            /** Preview Digest */
            preview_digest: string;
        };
        /** PropertyCsvPreviewRequest */
        PropertyCsvPreviewRequest: {
            /** Base Revision Id */
            base_revision_id: string;
            /** Csv */
            csv: string;
        };
        /** PropertyDefinitionDiffResponse */
        PropertyDefinitionDiffResponse: {
            /** Added */
            added: components["schemas"]["PropertyDefinitionResponse"][];
            /** Skipped */
            skipped: components["schemas"]["PropertyDefinitionResponse"][];
        };
        /** PropertyDefinitionResponse */
        PropertyDefinitionResponse: {
            /** Default Value */
            default_value: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "sheetset" | "sheet";
        };
        /** PropertyDiffResponse */
        PropertyDiffResponse: {
            /**
             * Action
             * @enum {string}
             */
            action: "add" | "delete" | "update";
            /** Affected Sheet Count */
            affected_sheet_count: number;
            /** After */
            after: string | components["schemas"]["PropertyDefinitionResponse"] | null;
            /** Before */
            before: string | components["schemas"]["PropertyDefinitionResponse"] | null;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "sheetset" | "sheet";
        };
        /** RepairActionResponse */
        RepairActionResponse: {
            /** After */
            after: {
                [key: string]: string | null;
            };
            /** Before */
            before: {
                [key: string]: string | null;
            };
            /** Code */
            code: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "deterministic" | "inferred";
            /** Message */
            message: string;
            /** Node Path */
            node_path: string;
            /** Object Id */
            object_id?: string | null;
        };
        /** RepairExecuteRequest */
        RepairExecuteRequest: {
            /** Base Revision Id */
            base_revision_id: string;
            /** Preview Digest */
            preview_digest: string;
        };
        /** RepairPreviewRequest */
        RepairPreviewRequest: {
            /** Base Revision Id */
            base_revision_id: string;
        };
        /** RepairPreviewResponse */
        RepairPreviewResponse: {
            /** Actions */
            actions: components["schemas"]["RepairActionResponse"][];
            /** Base Revision Id */
            base_revision_id: string;
            /** Blocking Issues */
            blocking_issues: components["schemas"]["DiagnosticResponse"][];
            /** Executable */
            executable: boolean;
            /** Preview Digest */
            preview_digest?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "VALID" | "REPAIRED" | "INVALID_REPAIR_REQUIRED" | "INVALID_UNRECOVERABLE";
            /** Workspace Id */
            workspace_id: string;
        };
        /** RestoreFileResponse */
        RestoreFileResponse: {
            /**
             * Action
             * @enum {string}
             */
            action: "replace" | "delete";
            /** Backup Hash */
            backup_hash?: string | null;
            /** Backup Identity */
            backup_identity?: number[] | null;
            /** Conflict */
            conflict: boolean;
            /** Current Hash */
            current_hash?: string | null;
            /** Expected Hash */
            expected_hash?: string | null;
            /** Path */
            path: string;
            /** Restore Hash */
            restore_hash?: string | null;
            /** Source Conflict */
            source_conflict: boolean;
        };
        /** RestorePreviewResponse */
        RestorePreviewResponse: {
            /** Base Revision Id */
            base_revision_id: string;
            /** Conflicts */
            conflicts: string[];
            /** Executable */
            executable: boolean;
            /** Files */
            files: components["schemas"]["RestoreFileResponse"][];
            /** Preview Digest */
            preview_digest: string;
            /** Revision Id */
            revision_id: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** RestoreRevisionExecuteRequest */
        RestoreRevisionExecuteRequest: {
            /** Base Revision Id */
            base_revision_id: string;
            /** Preview Digest */
            preview_digest: string;
        };
        /** RevisionResponse */
        RevisionResponse: {
            /** Before Hash */
            before_hash: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Operation Id */
            operation_id: string;
            /** Result Hash */
            result_hash: string;
            /** Revision Dir */
            revision_dir: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** SemanticDiffResponse */
        SemanticDiffResponse: {
            /** Dwgs */
            dwgs: components["schemas"]["DwgDiffResponse"][];
            /** Properties */
            properties: components["schemas"]["PropertyDiffResponse"][];
            /** Sheet Set */
            sheet_set: components["schemas"]["SheetSetFieldDiffResponse"][];
            structure: components["schemas"]["StructureDiffResponse"];
        };
        /** SheetResponse */
        SheetResponse: {
            /** Custom Properties */
            custom_properties: {
                [key: string]: string;
            };
            /** Id */
            id: string;
            layout: components["schemas"]["LayoutResponse"];
            /** Number */
            number: string;
            /** Title */
            title: string;
        };
        /** SheetSetFieldDiffResponse */
        SheetSetFieldDiffResponse: {
            /** After */
            after: string;
            /** Before */
            before: string;
            /**
             * Field
             * @constant
             */
            field: "name";
        };
        /** SheetSetResponse */
        SheetSetResponse: {
            /** Custom Properties */
            custom_properties: {
                [key: string]: string;
            };
            /** Database Id */
            database_id: string;
            /** Name */
            name: string;
            /** Property Definitions */
            property_definitions: components["schemas"]["PropertyDefinitionResponse"][];
            /** Sheet Count */
            sheet_count: number;
            /** Subset Count */
            subset_count: number;
            /** Subsets */
            subsets: components["schemas"]["SubsetResponse"][];
        };
        /** SourceBaselineResponse */
        SourceBaselineResponse: {
            /** Identity */
            identity: number[];
            /** Path */
            path: string;
            /** Requested Layouts */
            requested_layouts: string[];
            /** Sha256 */
            sha256: string;
            /** Source Types */
            source_types: ("existing_snapshot" | "template_layout")[];
        };
        /** StructureDiffResponse */
        StructureDiffResponse: {
            /** After */
            after: components["schemas"]["StructureSubsetResponse"][];
            /** Before */
            before: components["schemas"]["StructureSubsetResponse"][];
        };
        /** StructureSheetResponse */
        StructureSheetResponse: {
            /** Dwg File */
            dwg_file: string;
            /** Id */
            id: string;
            /** Layout Name */
            layout_name: string;
            /** Number */
            number: string;
            /** Position */
            position: number;
            /** Suffix */
            suffix: string;
            /** Title */
            title: string;
        };
        /** StructureSubsetResponse */
        StructureSubsetResponse: {
            /** Display Name */
            display_name: string;
            /** Dwg File */
            dwg_file: string;
            /** Id */
            id: string;
            /** Number Range */
            number_range: string;
            /** Position */
            position: number;
            /** Sheets */
            sheets: components["schemas"]["StructureSheetResponse"][];
            /** Title */
            title: string;
        };
        /** SubsetOperationResponse */
        SubsetOperationResponse: {
            /**
             * Cad Operation
             * @enum {string}
             */
            cad_operation: "none" | "rename_only" | "rebuild";
            /** In Cardinality Scope */
            in_cardinality_scope: boolean;
            /** Subset Id */
            subset_id: string;
            /** Target File */
            target_file: string;
        };
        /** SubsetResponse */
        SubsetResponse: {
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Number Range */
            number_range: string;
            /** Order */
            order: number;
            /** Sheets */
            sheets: components["schemas"]["SheetResponse"][];
            /** Title */
            title: string;
        };
        /** UpdateSheetPropertiesCommand */
        UpdateSheetPropertiesCommand: {
            /** Custom Properties */
            custom_properties: {
                [key: string]: string;
            };
            /** Sheet Id */
            sheet_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "update_sheet_properties";
        };
        /** UpdateSheetSetCommand */
        UpdateSheetSetCommand: {
            /** Custom Properties */
            custom_properties?: {
                [key: string]: string;
            } | null;
            /** Name */
            name?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "update_sheet_set";
        };
        /** UpdateSubsetTitleCommand */
        UpdateSubsetTitleCommand: {
            /** Subset Id */
            subset_id: string;
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "update_subset_title";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceResponse */
        WorkspaceResponse: {
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticResponse"][];
            /** Dst Path */
            dst_path: string;
            dst_validation: components["schemas"]["DstValidationResponse"];
            /** Id */
            id: string;
            /** Revision Id */
            revision_id: string;
            /** Root */
            root: string;
            sheet_set: components["schemas"]["SheetSetResponse"];
            /** Unreferenced Dwgs */
            unreferenced_dwgs: string[];
        };
        /** XmlExecuteRequest */
        XmlExecuteRequest: {
            /** Base Revision Id */
            base_revision_id: string;
            /**
             * Destination
             * Format: path
             */
            destination: string;
            /** Destination Revision Id */
            destination_revision_id?: string | null;
            /** Preview Digest */
            preview_digest: string;
            /** Xml */
            xml: string;
        };
        /** XmlPreviewRequest */
        XmlPreviewRequest: {
            /** Base Revision Id */
            base_revision_id: string;
            /** Destination */
            destination?: string | null;
            /** Xml */
            xml: string;
        };
        /** XmlPreviewResponse */
        XmlPreviewResponse: {
            /** Base Revision Id */
            base_revision_id: string;
            /** Changes */
            changes: {
                [key: string]: unknown;
            }[];
            /** Destination Revision Id */
            destination_revision_id?: string | null;
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticResponse"][];
            /** Executable */
            executable: boolean;
            /** Preview Digest */
            preview_digest: string;
            /** Sheet Count After */
            sheet_count_after: number;
            /** Sheet Count Before */
            sheet_count_before: number;
            /** Subset Count After */
            subset_count_after: number;
            /** Subset Count Before */
            subset_count_before: number;
            /** Workspace Id */
            workspace_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    custom_property_template_api_custom_properties_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_layout_names_api_layout_names_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutNamesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutNamesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisions_api_revisions_get: {
        parameters: {
            query?: {
                workspace_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_system_cad_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CadCapabilitiesResponse"];
                };
            };
        };
    };
    get_workspace_api_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_api_workspaces__workspace_id__changes_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_workspaces__workspace_id__changes_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_custom_properties_api_workspaces__workspace_id__custom_properties_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_custom_properties_api_workspaces__workspace_id__custom_properties_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyCsvExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_custom_property_import_api_workspaces__workspace_id__custom_properties_import_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyCsvPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_workspaces__workspace_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_draft_api_workspaces__workspace_id__draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_draft_api_workspaces__workspace_id__draft_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_execute_api_workspaces__workspace_id__repairs_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_preview_api_workspaces__workspace_id__repairs_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepairPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_revision_api_workspaces__workspace_id__revisions__revision_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreRevisionExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_preview_api_workspaces__workspace_id__revisions__revision_id__restore_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestorePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_dst_api_workspaces__workspace_id__xml_export_dst_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["XmlExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_xml_api_workspaces__workspace_id__xml_import_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["XmlPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XmlPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_workspace_api_workspaces_open_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
