@echo off
setlocal enabledelayedexpansion
rem DST Manager 最终用户环境初始化脚本（打包分发版，见 ARCH-DM-002）。
rem 用法：与本程序 DSTManager.exe 放在同一目录，双击运行；在本目录生成/补全 .env。
rem 幂等：不覆盖已有 .env 与已有配置项，只补缺失项。
rem 编码说明：本脚本必须保存为 GBK（ANSI，zh-CN 系统默认代码页）。
rem UTF-8 批处理在 cmd 下多字节解析不可靠（实测会吞字符），故沿用 SCR 先例
rem 作为仓库 UTF-8 规则的例外；.env 模板注释刻意全部使用 ASCII，
rem 保证写出的 .env 恒为合法 UTF-8（pydantic-settings 按 utf-8 读取）。
rem 版本兼容组（.NET 插件向前兼容口径，见 ARCH-DM-002）：
rem   2015-2019 -> 2016 桶（DST_MANAGER_AUTOCAD_2016_CONSOLE）
rem   2020-2024 -> 2020 桶（DST_MANAGER_AUTOCAD_2020_CONSOLE）
rem   2013/2014 -> 警告后仍写入 2016 桶（2016 构建的插件在旧版加载无官方保证）
rem   2025 及以上不受支持（改用 .NET 8，与随包插件不兼容）；accoreconsole 自 2013 起才有。
rem 测试钩子：DST_SETUP_AUTODESK_ROOT（覆盖扫描根目录）、
rem DST_SETUP_SKIP_REGISTRY=1（跳过注册表探测）、
rem DST_SETUP_NO_PAUSE=1（结束不暂停，供自动化测试）。

set "APP_DIR=%~dp0"
set "ENV_FILE=%APP_DIR%.env"
set "AUTODESK_ROOT=%ProgramFiles%\Autodesk"
if defined DST_SETUP_AUTODESK_ROOT set "AUTODESK_ROOT=%DST_SETUP_AUTODESK_ROOT%"

set "CONSOLE_2016="
set "CONSOLE_2020="

echo === DST Manager 环境初始化 ===
echo 程序目录：%APP_DIR%
echo 扫描根目录：%AUTODESK_ROOT%
echo.

rem --- 按 2013-2024 升序探测：同一兼容组内后发现的版本覆盖前者，即组内取最新 ---
call :detect 2013 R19.0
call :detect 2014 R19.1
call :detect 2015 R20.0
call :detect 2016 R20.1
call :detect 2017 R21.0
call :detect 2018 R22.0
call :detect 2019 R23.0
call :detect 2020 R23.1
call :detect 2021 R24.0
call :detect 2022 R24.1
call :detect 2023 R24.2
call :detect 2024 R24.3

rem --- 2025 及以上：明确提示不支持 ---
for %%y in (2025 2026 2027 2028 2029) do if exist "%AUTODESK_ROOT%\AutoCAD %%y\accoreconsole.exe" echo [警告] 检测到 AutoCAD %%y：2025 及以上版本改用 .NET 8 运行时，与随包插件不兼容，不受支持。

call :write_env

echo.
echo === 完成 ===
if defined CONSOLE_2016 echo 2016 桶 Core Console：%CONSOLE_2016%
if defined CONSOLE_2020 echo 2020 桶 Core Console：%CONSOLE_2020%
if not defined CONSOLE_2016 if not defined CONSOLE_2020 echo [提示] 未发现受支持的 AutoCAD（2013-2024），请手工编辑 .env 填写 DST_MANAGER_AUTOCAD_2016_CONSOLE / DST_MANAGER_AUTOCAD_2020_CONSOLE。
echo 配置修改完成后重启 DST Manager 生效。
echo.
if not defined DST_SETUP_NO_PAUSE pause
exit /b 0

:detect
rem %1=年份 %2=注册表主键 Rxx.x；先查注册表 AcadLocation，再回退默认安装目录扫描
set "year=%~1"
set "regkey=%~2"
set "acaddir="
if defined DST_SETUP_SKIP_REGISTRY goto scan_dir
for /f "tokens=2*" %%a in ('reg query "HKLM\SOFTWARE\Autodesk\AutoCAD\%regkey%" /s /v AcadLocation 2^>nul ^| findstr /i "AcadLocation"') do set "acaddir=%%b"
if not defined acaddir goto scan_dir
if exist "!acaddir!\accoreconsole.exe" (
    call :record "!year!" "!acaddir!"
    goto :eof
)
:scan_dir
set "acaddir=%AUTODESK_ROOT%\AutoCAD %year%"
if exist "!acaddir!\accoreconsole.exe" call :record "!year!" "!acaddir!"
goto :eof

:record
rem %1=年份 %2=安装目录；按兼容组写入对应桶的候选路径
set "year=%~1"
set "console=%~2\accoreconsole.exe"
echo [发现] AutoCAD %year%：%console%
if %year% LSS 2015 (
    echo [警告] AutoCAD %year% 与按 2016 程序集构建的随包插件兼容性未经官方保证，可能加载失败；已按 2016 桶写入，请用 doctor 自检或实际运行验证。
    set "CONSOLE_2016=!console!"
    goto :eof
)
if %year% LSS 2020 (
    set "CONSOLE_2016=!console!"
    goto :eof
)
set "CONSOLE_2020=!console!"
goto :eof

:write_env
if not exist "%ENV_FILE%" (
    call :write_template
    goto :eof
)
rem 已有 .env：只补缺失键，绝不覆盖已有配置
set "CHANGED=0"
if defined CONSOLE_2016 call :ensure_key DST_MANAGER_AUTOCAD_2016_CONSOLE "!CONSOLE_2016!"
if defined CONSOLE_2020 call :ensure_key DST_MANAGER_AUTOCAD_2020_CONSOLE "!CONSOLE_2020!"
if "%CHANGED%"=="0" echo [跳过] .env 已存在且配置完整，未做修改。
goto :eof

:ensure_key
rem %1=键名 %2=值；仅当 .env 中不存在该键（行首精确匹配）时追加
findstr /b /c:"%1=" "%ENV_FILE%" >nul 2>&1
if not errorlevel 1 goto :eof
>>"%ENV_FILE%" echo %1=%~2
echo [写入] %1=%2
set "CHANGED=1"
goto :eof

:write_template
rem .env 不存在：按 .env.example 同构生成完整模板，未探测到的键保留注释占位
rem 注意：模板注释必须全部使用 ASCII（写出文件恒为合法 UTF-8，见文件头说明）
echo [生成] %ENV_FILE%
> "%ENV_FILE%" echo # DST Manager configuration generated by setup.bat. Edit freely; restart the app to apply.
>> "%ENV_FILE%" echo.
>> "%ENV_FILE%" echo # Add number suffix to sheet titles automatically. Default: true
>> "%ENV_FILE%" echo EnableAddNumberSuffix=true
>> "%ENV_FILE%" echo # 1 = Chinese numeral suffix, 2 = numeric suffix. Default: 1
>> "%ENV_FILE%" echo NumberSuffixType=1
>> "%ENV_FILE%" echo.
>> "%ENV_FILE%" echo # --- AutoCAD Core Console paths ---
>> "%ENV_FILE%" echo # Compatibility mapping: AutoCAD 2015-2019 uses the 2016 entry, 2020-2024 uses the 2020 entry.
>> "%ENV_FILE%" echo # Worker plugin DLLs are resolved automatically to autocad2016/ autocad2020/ next to the exe.
if defined CONSOLE_2016 goto tpl_2016_set
>> "%ENV_FILE%" echo # DST_MANAGER_AUTOCAD_2016_CONSOLE=C:\Program Files\Autodesk\AutoCAD 2016\accoreconsole.exe
goto tpl_2020
:tpl_2016_set
>> "%ENV_FILE%" echo DST_MANAGER_AUTOCAD_2016_CONSOLE=!CONSOLE_2016!
:tpl_2020
if defined CONSOLE_2020 goto tpl_2020_set
>> "%ENV_FILE%" echo # DST_MANAGER_AUTOCAD_2020_CONSOLE=C:\Program Files\Autodesk\AutoCAD 2020\accoreconsole.exe
goto tpl_done
:tpl_2020_set
>> "%ENV_FILE%" echo DST_MANAGER_AUTOCAD_2020_CONSOLE=!CONSOLE_2020!
:tpl_done
>> "%ENV_FILE%" echo.
>> "%ENV_FILE%" echo # --- Optional settings ---
>> "%ENV_FILE%" echo # CAD execution timeout in seconds. Default: 600
>> "%ENV_FILE%" echo # DST_MANAGER_CAD_TIMEOUT_SECONDS=600
>> "%ENV_FILE%" echo # Core Console parallelism per task. Default: 4, range 1-10
>> "%ENV_FILE%" echo # DST_MANAGER_CAD_MAX_PARALLEL=4
>> "%ENV_FILE%" echo # Worker heartbeat lease in seconds. Default: 120
>> "%ENV_FILE%" echo # DST_MANAGER_WORKER_LEASE_SECONDS=120
goto :eof
