<script setup lang="ts">
// 完整变更预览面板（PLAN-DM-021 Task 8，I18N-07/08）：静态文本走语义键，动态句子用命名参数/复数；
// 字段名、路径、哈希、DWG/布局名与协议 action 值保持原样；分隔符取自语言包，不在模板写死全角标点。
import {useI18n} from "vue-i18n";
import type {CadGroup,CardinalityFrontier,DerivedSubset,ExecutionEstimate,Preview,SemanticDiff,SourceBaseline,SubsetOperation} from "../api/contracts";
defineProps<{preview:Preview;semanticDiff:SemanticDiff;estimate:ExecutionEstimate|null;cadValidationDeferred:boolean;cardinalityFrontier:CardinalityFrontier|null;subsetOperations:SubsetOperation[];sourceBaselines:SourceBaseline[];derivedSubsets:DerivedSubset[];groups:CadGroup[]}>();
const {t}=useI18n();

function valueText(value:unknown){if(value===null||value===undefined||value==="")return "—";return typeof value==="object"?JSON.stringify(value):String(value)}
// CAD 操作码 → 语义键（common.cadOperation）：预览与任务面板共用；未知码回退「未知 CAD 操作：码」
const CAD_OPERATION_KEYS:Record<string,string>={rename_only:"common.cadOperation.renameOnly",rebuild:"common.cadOperation.rebuild",none:"common.cadOperation.none"};
function operationLabel(operation?:string|null){if(!operation)return t("common.cadOperation.missing");const key=CAD_OPERATION_KEYS[operation];return key?t(key):t("common.cadOperation.unknown",{operation})}
</script>
<template><section class="panel preview"><h2>{{ $t("shell.preview.title") }}</h2>
  <section v-if="estimate"><h3>{{ $t("shell.preview.estimateTitle") }}</h3><p>{{ $t("shell.preview.estimateSummary",{count:estimate.core_console_count,concurrency:estimate.concurrency,lower:Math.round(estimate.duration_ms.lower/1000),upper:Math.round(estimate.duration_ms.upper/1000)},estimate.core_console_count) }}</p><ul><li v-for="source in estimate.sources" :key="source.cad_operation">{{operationLabel(source.cad_operation)}}：{{source.source==='history'?$t("shell.preview.sourceHistory",{count:source.sample_count},source.sample_count):$t("shell.preview.sourceFallback",{count:source.sample_count},source.sample_count)}}</li></ul></section>
  <section v-if="semanticDiff.sheet_set?.length"><h3>{{ $t("shell.preview.sheetSetDiffTitle") }}</h3><table><thead><tr><th>{{ $t("shell.preview.field") }}</th><th>{{ $t("shell.preview.beforeValue") }}</th><th>{{ $t("shell.preview.afterValue") }}</th></tr></thead><tbody><tr v-for="item in semanticDiff.sheet_set" :key="item.field"><td>{{item.field}}</td><td>{{valueText(item.before)}}</td><td>{{valueText(item.after)}}</td></tr></tbody></table></section>
  <section><h3>{{ $t("shell.preview.structureTitle") }}</h3><div class="group-grid"><article v-for="side in ['before','after']" :key="side"><h4>{{side==='before'?$t("shell.preview.beforeSide"):$t("shell.preview.afterSide")}}</h4><table><thead><tr><th>{{ $t("shell.preview.position") }}</th><th>{{ $t("shell.preview.subsetSheet") }}</th><th>{{ $t("shell.preview.numberRangeSuffix") }}</th><th>{{ $t("shell.preview.dwgLayout") }}</th></tr></thead><tbody><template v-for="subset in semanticDiff.structure?.[side]??[]" :key="subset.id"><tr><td>{{subset.position}}</td><td>{{subset.display_name}} · {{subset.title}}</td><td>{{subset.number_range}}</td><td>{{subset.dwg_file}}</td></tr><tr v-for="sheet in subset.sheets" :key="sheet.id"><td>{{subset.position}}.{{sheet.position}}</td><td>{{sheet.number}} · {{sheet.title}}</td><td>{{sheet.suffix||'—'}}</td><td>{{sheet.dwg_file}} · {{sheet.layout_name}}</td></tr></template></tbody></table></article></div></section>
  <section v-if="semanticDiff.properties?.length"><h3>{{ $t("shell.preview.propertiesDiffTitle") }}</h3><table><thead><tr><th>{{ $t("shell.preview.operation") }}</th><th>{{ $t("shell.preview.scope") }}</th><th>{{ $t("shell.preview.name") }}</th><th>{{ $t("shell.preview.beforeValue") }}</th><th>{{ $t("shell.preview.afterValue") }}</th><th>{{ $t("shell.preview.affectedSheets") }}</th></tr></thead><tbody><tr v-for="item in semanticDiff.properties" :key="`${item.action}-${item.type}-${item.name}`"><td>{{item.action}}</td><td>{{item.type}}</td><td>{{item.name}}</td><td>{{valueText(item.before)}}</td><td>{{valueText(item.after)}}</td><td>{{item.affected_sheet_count}}</td></tr></tbody></table></section>
  <section v-if="semanticDiff.dwgs?.length"><h3>{{ $t("shell.preview.dwgsDiffTitle") }}</h3><table><thead><tr><th>{{ $t("shell.preview.operation") }}</th><th>{{ $t("shell.preview.beforeFileLayout") }}</th><th>{{ $t("shell.preview.afterFileLayout") }}</th></tr></thead><tbody><tr v-for="item in semanticDiff.dwgs" :key="`${item.action}-${item.subset_id}`"><td>{{item.action}}</td><td>{{item.before?.file??'—'}} · {{item.before?.layouts?.join(t("common.listSeparator"))??'—'}}</td><td>{{item.after?.file??'—'}} · {{item.after?.layouts?.join(t("common.listSeparator"))??'—'}}</td></tr></tbody></table></section>
  <section v-if="cadValidationDeferred" class="notice"><h3>{{ $t("shell.preview.cadValidationTitle") }}</h3><p>{{ $t("shell.preview.cadValidationDeferred") }}</p></section><section v-if="cardinalityFrontier"><h3>{{ $t("shell.preview.cardinalityTitle") }}</h3><p>{{ $t("shell.preview.cardinalityDetail",{index:cardinalityFrontier.index + 1}) }}</p></section>
  <section v-if="subsetOperations.length"><h3>{{ $t("shell.preview.subsetOperationsTitle") }}</h3><table><thead><tr><th>{{ $t("shell.preview.subset") }}</th><th>{{ $t("shell.preview.operation") }}</th><th>{{ $t("shell.preview.targetDwg") }}</th><th>{{ $t("shell.preview.cardinalityScopeRange") }}</th></tr></thead><tbody><tr v-for="item in subsetOperations" :key="item.subset_id"><td>{{item.subset_id}}</td><td>{{operationLabel(item.cad_operation)}}</td><td>{{item.target_file}}</td><td>{{item.in_cardinality_scope?$t("shell.preview.yes"):$t("shell.preview.no")}}</td></tr></tbody></table></section>
  <section v-if="sourceBaselines.length"><h3>{{ $t("shell.preview.sourceBaselinesTitle") }}</h3><table><thead><tr><th>{{ $t("shell.preview.sourcePath") }}</th><th>SHA-256</th><th>{{ $t("shell.preview.requestedLayouts") }}</th><th>{{ $t("shell.preview.sourceTypes") }}</th></tr></thead><tbody><tr v-for="item in sourceBaselines" :key="item.path"><td>{{item.path}}</td><td>{{item.sha256}}</td><td>{{item.requested_layouts?.join(t("common.listSeparator"))}}</td><td>{{item.source_types?.join(t("common.listSeparator"))}}</td></tr></tbody></table></section>
  <section v-if="preview.execution_intent"><h3>{{ $t("shell.preview.numberRangeChangeTitle") }}</h3><table v-if="derivedSubsets.length"><thead><tr><th>{{ $t("shell.preview.serverNumberRange") }}</th><th>{{ $t("shell.preview.serverDisplayName") }}</th><th>{{ $t("shell.preview.serverTitle") }}</th></tr></thead><tbody><tr v-for="subset in derivedSubsets" :key="subset.acsm_id"><td>{{subset.number_range}}</td><td>{{subset.display_name}}</td><td>{{subset.title}}</td></tr></tbody></table></section>
  <section><h3>{{ $t("shell.preview.changesTitle") }}</h3><ul><li v-for="(change,index) in preview.changes" :key="index"><strong>{{change.type}}</strong><span v-if="change.affected_sheet_count!==undefined"> · {{ $t("shell.preview.affectedCount",{count:change.affected_sheet_count}) }}</span></li></ul></section>
  <section v-if="groups.length"><h3>{{ $t("shell.preview.groupsTitle") }}</h3><div class="group-grid"><article v-for="group in groups" :key="group.subset_id" class="execution-group"><strong>{{operationLabel(group.cad_operation)}}</strong><h4>{{group.subset_name}}</h4><p>{{group.target_file}}</p><table><thead><tr><th>{{ $t("shell.preview.sheetNumber") }}</th><th>{{ $t("shell.preview.serverTitle") }}</th><th>{{ $t("shell.preview.targetLayout") }}</th></tr></thead><tbody><tr v-for="layout in group.layouts" :key="layout.sheet_id"><td>{{layout.number}}</td><td>{{layout.title}}</td><td>{{layout.target_layout}}</td></tr></tbody></table></article></div></section>
  <section><h3>{{ $t("shell.preview.diagnosticsTitle") }}</h3><ul class="diagnostics"><li v-for="item in preview.diagnostics" :key="item.code+item.message" :class="item.severity"><b>{{item.code}}</b>{{ $t("shell.preview.diagSeparator") }}{{item.message}}</li><li v-if="!preview.diagnostics?.length">{{ $t("shell.overlay.empty") }}</li></ul></section><section><h3>{{ $t("shell.preview.affectedFilesTitle") }}</h3><ul><li v-for="file in preview.affected_files" :key="file">{{file}}</li></ul></section>
</section></template>
