<script setup lang="ts">
import type {CadGroup,CardinalityFrontier,DerivedSubset,ExecutionEstimate,Preview,SemanticDiff,SourceBaseline,SubsetOperation} from "../api/contracts";
defineProps<{preview:Preview;semanticDiff:SemanticDiff;estimate:ExecutionEstimate|null;cadValidationDeferred:boolean;cardinalityFrontier:CardinalityFrontier|null;subsetOperations:SubsetOperation[];sourceBaselines:SourceBaseline[];derivedSubsets:DerivedSubset[];groups:CadGroup[];writesDisabled:boolean}>();
defineEmits<{execute:[]}>();
function valueText(value:unknown){if(value===null||value===undefined||value==="")return "—";return typeof value==="object"?JSON.stringify(value):String(value)}
function operationLabel(operation?:string|null){if(operation==="rename_only")return "批量改名布局";if(operation==="rebuild")return "清除并重建布局";if(operation==="none")return "无需 CAD 操作";if(!operation)return "未提供 CAD 操作";return `未知 CAD 操作：${operation}`}
</script>
<template><section class="panel preview"><h2>完整变更预览</h2>
  <section v-if="estimate"><h3>Core Console 估算</h3><p>预计 {{estimate.core_console_count}} 个任务 · 并发度 {{estimate.concurrency}} · 预计耗时 {{Math.round(estimate.duration_ms.lower/1000)}}–{{Math.round(estimate.duration_ms.upper/1000)}} 秒（估算值）</p><ul><li v-for="source in estimate.sources" :key="source.cad_operation">{{operationLabel(source.cad_operation)}}：{{source.source==='history'?`历史样本 ${source.sample_count} 个`:`保守 fallback v1（历史样本 ${source.sample_count} 个）`}}</li></ul></section>
  <section v-if="semanticDiff.sheet_set?.length"><h3>图纸集字段差异</h3><table><thead><tr><th>字段</th><th>前值</th><th>后值</th></tr></thead><tbody><tr v-for="item in semanticDiff.sheet_set" :key="item.field"><td>{{item.field}}</td><td>{{valueText(item.before)}}</td><td>{{valueText(item.after)}}</td></tr></tbody></table></section>
  <section><h3>前后有序结构</h3><div class="group-grid"><article v-for="side in ['before','after']" :key="side"><h4>{{side==='before'?'变更前':'变更后'}}</h4><table><thead><tr><th>位置</th><th>子集 / 图纸</th><th>图号范围 / 后缀</th><th>DWG / 布局</th></tr></thead><tbody><template v-for="subset in semanticDiff.structure?.[side]??[]" :key="subset.id"><tr><td>{{subset.position}}</td><td>{{subset.display_name}} · {{subset.title}}</td><td>{{subset.number_range}}</td><td>{{subset.dwg_file}}</td></tr><tr v-for="sheet in subset.sheets" :key="sheet.id"><td>{{subset.position}}.{{sheet.position}}</td><td>{{sheet.number}} · {{sheet.title}}</td><td>{{sheet.suffix||'—'}}</td><td>{{sheet.dwg_file}} · {{sheet.layout_name}}</td></tr></template></tbody></table></article></div></section>
  <section v-if="semanticDiff.properties?.length"><h3>属性差异</h3><table><thead><tr><th>操作</th><th>作用域</th><th>名称</th><th>前值</th><th>后值</th><th>受影响图纸</th></tr></thead><tbody><tr v-for="item in semanticDiff.properties" :key="`${item.action}-${item.type}-${item.name}`"><td>{{item.action}}</td><td>{{item.type}}</td><td>{{item.name}}</td><td>{{valueText(item.before)}}</td><td>{{valueText(item.after)}}</td><td>{{item.affected_sheet_count}}</td></tr></tbody></table></section>
  <section v-if="semanticDiff.dwgs?.length"><h3>DWG 与布局差异</h3><table><thead><tr><th>操作</th><th>变更前文件 / 布局</th><th>变更后文件 / 布局</th></tr></thead><tbody><tr v-for="item in semanticDiff.dwgs" :key="`${item.action}-${item.subset_id}`"><td>{{item.action}}</td><td>{{item.before?.file??'—'}} · {{item.before?.layouts?.join('、')??'—'}}</td><td>{{item.after?.file??'—'}} · {{item.after?.layouts?.join('、')??'—'}}</td></tr></tbody></table></section>
  <section v-if="cadValidationDeferred" class="notice"><h3>CAD 校验</h3><p>CAD 布局校验将在确认后执行</p></section><section v-if="cardinalityFrontier"><h3>数量变化前沿</h3><p>数量变化前沿：第 {{cardinalityFrontier.index + 1}} 个子集</p></section>
  <section v-if="subsetOperations.length"><h3>子集 CAD 操作</h3><table><thead><tr><th>子集</th><th>操作</th><th>目标 DWG</th><th>数量前沿范围</th></tr></thead><tbody><tr v-for="item in subsetOperations" :key="item.subset_id"><td>{{item.subset_id}}</td><td>{{operationLabel(item.cad_operation)}}</td><td>{{item.target_file}}</td><td>{{item.in_cardinality_scope?'是':'否'}}</td></tr></tbody></table></section>
  <section v-if="sourceBaselines.length"><h3>来源基准</h3><table><thead><tr><th>来源路径</th><th>SHA-256</th><th>请求布局</th><th>来源类型</th></tr></thead><tbody><tr v-for="item in sourceBaselines" :key="item.path"><td>{{item.path}}</td><td>{{item.sha256}}</td><td>{{item.requested_layouts?.join('、')}}</td><td>{{item.source_types?.join('、')}}</td></tr></tbody></table></section>
  <section v-if="preview.execution_intent"><h3>图号范围变化</h3><table v-if="derivedSubsets.length"><thead><tr><th>服务端图号范围</th><th>服务端显示名</th><th>服务端标题</th></tr></thead><tbody><tr v-for="subset in derivedSubsets" :key="subset.acsm_id"><td>{{subset.number_range}}</td><td>{{subset.display_name}}</td><td>{{subset.title}}</td></tr></tbody></table></section>
  <section><h3>兼容变更清单</h3><ul><li v-for="(change,index) in preview.changes" :key="index"><strong>{{change.type}}</strong><span v-if="change.affected_sheet_count!==undefined"> · 受影响图纸 {{change.affected_sheet_count}}</span></li></ul></section>
  <section v-if="groups.length"><h3>CAD 执行分组</h3><div class="group-grid"><article v-for="group in groups" :key="group.subset_id" class="execution-group"><strong>{{operationLabel(group.cad_operation)}}</strong><h4>{{group.subset_name}}</h4><p>{{group.target_file}}</p><table><thead><tr><th>图号</th><th>服务端标题</th><th>目标布局</th></tr></thead><tbody><tr v-for="layout in group.layouts" :key="layout.sheet_id"><td>{{layout.number}}</td><td>{{layout.title}}</td><td>{{layout.target_layout}}</td></tr></tbody></table></article></div></section>
  <section><h3>诊断</h3><ul class="diagnostics"><li v-for="item in preview.diagnostics" :key="item.code+item.message" :class="item.severity"><b>{{item.code}}</b>：{{item.message}}</li><li v-if="!preview.diagnostics?.length">无阻断诊断</li></ul></section><section><h3>受影响文件</h3><ul><li v-for="file in preview.affected_files" :key="file">{{file}}</li></ul></section>
  <button class="primary" :disabled="writesDisabled||preview.executable===false" @click="$emit('execute')">确认并执行</button>
</section></template>
